#!/usr/bin/env node 

var program = require('commander');

program
  .version('0.1.0')
  .usage('<command> [options]')
  .command('init', 'generate a new project from a template')
  .command('list', 'list available official templates')
  .command('build', 'prototype a new project')
  .parse(process.argv)
